theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
title: bold360 Android SDK
baseurl: "/bold360-mobile-docs-android"
url: "https://logmein-bold-mobile.github.io" 
# url: "http://localhost:4000"

color_scheme: android-scheme


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"