theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
title: bold360 Android SDK
baseurl: "/bold360-mobile-docs-android"
url: "https://logmein-bold-mobile.github.io" 
# url: "http://localhost:4000"

color_scheme: android-scheme

<<<<<<< HEAD

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
=======
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
>>>>>>> 4374e807ca709bd3868d54c564d18821105e587e
