theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
title: bold360 Android SDK
# baseurl: "/bold360-mobile-docs-android"
url: "https://logmein-bold-mobile.github.io/bold360-mobile-docs-android" 


color_scheme: android-scheme


